version: "3.9"

services:
  work:
    build: .
    volumes:
      - .:/home/tackman/work
    privileged: true
    ports:
      - 8081:8080
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    entrypoint: "code-server --auth none --bind-addr=0.0.0.0:8080 /home/tackman/work"
    networks:
      - main

networks:
  main:
    driver: bridge


